export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'

export const LOCATIONS_REQUEST = 'LOCATIONS_REQUEST'
export const ADDRESS_REQUEST = 'ADDRESS_REQUEST'
export const ADDRESS_SUCCESS = 'ADDRESS_SUCCESS'
export const ADDRESS_ERROR = 'ADDRESS_ERROR'

export const DRIVERS_REQUEST = 'DRIVERS_REQUEST'
export const DRIVERS_SUCCESS = 'DRIVERS_SUCCESS'
export const DRIVERS_ERROR = 'DRIVERS_ERROR'

export const ORDER_CREATE = 'ORDER_CREATE'
export const ORDER_SUCCESS = 'ORDER_SUCCESS'
export const ORDER_ERROR = 'ORDER_ERROR'
